---
- name: Loop Condition
  hosts: web
  become: yes
  tasks:
    - name: Install package
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - unzip
        - tree
      when: item != "tree"
